version: "3.3"

services:

  postgres:
    image: mdillon/postgis:11-alpine
    env_file:
      - docker/database.env
    volumes:
      - django-ninja-backend-pgadmin-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django-ninja-backend-docker-network

  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - "6379:6379"
    networks:
      - django-ninja-backend-docker-network

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    image: django-ninja-backend/python
    command: daphne core.asgi:application --port 8000 --bind 0.0.0.0 -v2
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - docker/database.env
      - docker/python.env
    depends_on:
      - postgres
      - redis
    networks:
      - django-ninja-backend-docker-network

volumes:
  django-ninja-backend-pgadmin-data:


networks:
  django-ninja-backend-docker-network:
    driver: bridge